// frontend/src/shared/utils/deductionsByState.js
export const deductionsByState = {
  Alabama: { standardDeduction: 4000, notes: 'Itemized allowed if higher than standard.' },
  Alaska: { standardDeduction: 0, notes: 'No state income tax.' },
  Arizona: { standardDeduction: 13850, notes: 'Matches federal standard deduction for 2025.' },
  Arkansas: { standardDeduction: 2200, notes: 'Low standard deduction; itemized often preferred.' },
  California: { standardDeduction: 10394, notes: 'Higher for joint filers; itemized common.' },
  Colorado: { standardDeduction: 13850, notes: 'Matches federal standard deduction.' },
  Connecticut: { standardDeduction: 0, notes: 'No standard deduction; itemized required.' },
  Delaware: { standardDeduction: 3250, notes: 'Lower than federal; itemized often used.' },
  Florida: { standardDeduction: 0, notes: 'No state income tax.' },
  Georgia: { standardDeduction: 12000, notes: 'Increased for 2025; itemized allowed.' },
  Hawaii: { standardDeduction: 2200, notes: 'Low standard deduction; itemized common.' },
  Idaho: { standardDeduction: 13850, notes: 'Matches federal standard deduction for 2025.' },
  Illinois: { standardDeduction: 0, notes: 'Flat tax rate; no standard deduction.' },
  Indiana: { standardDeduction: 0, notes: 'Flat tax rate; no standard deduction.' },
  Iowa: { standardDeduction: 0, notes: 'No standard deduction; itemized required.' },
  Kansas: { standardDeduction: 3500, notes: 'Lower than federal; itemized allowed.' },
  Kentucky: { standardDeduction: 2760, notes: 'Low standard deduction; itemized common.' },
  Louisiana: { standardDeduction: 0, notes: 'No standard deduction; itemized required.' },
  Maine: { standardDeduction: 13850, notes: 'Matches federal standard deduction.' },
  Maryland: { standardDeduction: 2300, notes: 'Low standard deduction; itemized common.' },
  Massachusetts: { standardDeduction: 0, notes: 'No standard deduction; flat tax rate.' },
  Michigan: { standardDeduction: 0, notes: 'Flat tax rate; no standard deduction.' },
  Minnesota: { standardDeduction: 13850, notes: 'Matches federal standard deduction.' },
  Mississippi: { standardDeduction: 2300, notes: 'Low standard deduction.' },
  Missouri: { standardDeduction: 13850, notes: 'Matches federal standard deduction.' },
  Montana: { standardDeduction: 5100, notes: 'Lower than federal; itemized allowed.' },
  Nebraska: { standardDeduction: 7800, notes: 'Lower than federal; itemized allowed.' },
  Nevada: { standardDeduction: 0, notes: 'No state income tax.' },
  NewHampshire: { standardDeduction: 0, notes: 'No income tax on earned income.' },
  NewJersey: { standardDeduction: 0, notes: 'No standard deduction; itemized required.' },
  NewMexico: { standardDeduction: 13850, notes: 'Matches federal standard deduction.' },
  NewYork: { standardDeduction: 8000, notes: 'Lower than federal; itemized common.' },
  NorthCarolina: { standardDeduction: 12750, notes: 'Close to federal standard deduction.' },
  NorthDakota: { standardDeduction: 13850, notes: 'Matches federal standard deduction.' },
  Ohio: { standardDeduction: 0, notes: 'No standard deduction; flat tax rate.' },
  Oklahoma: { standardDeduction: 6300, notes: 'Lower than federal; itemized allowed.' },
  Oregon: { standardDeduction: 2430, notes: 'Low standard deduction; itemized common.' },
  Pennsylvania: { standardDeduction: 0, notes: 'Flat tax rate; no standard deduction.' },
  RhodeIsland: { standardDeduction: 9600, notes: 'Lower than federal; itemized allowed.' },
  SouthCarolina: { standardDeduction: 13850, notes: 'Matches federal standard deduction.' },
  SouthDakota: { standardDeduction: 0, notes: 'No state income tax.' },
  Tennessee: { standardDeduction: 0, notes: 'No state income tax.' },
  Texas: { standardDeduction: 0, notes: 'No state income tax.' },
  Utah: { standardDeduction: 0, notes: 'Flat tax rate; no standard deduction.' },
  Vermont: { standardDeduction: 13850, notes: 'Matches federal standard deduction.' },
  Virginia: { standardDeduction: 8000, notes: 'Lower than federal; itemized allowed.' },
  Washington: { standardDeduction: 0, notes: 'No state income tax.' },
  WestVirginia: { standardDeduction: 0, notes: 'No standard deduction; itemized required.' },
  Wisconsin: { standardDeduction: 10000, notes: 'Credits for renters, child care, and retirement.' },
  Wyoming: { standardDeduction: 0, notes: 'No state income tax.' },
};